apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: student-261347
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:latest #jakuboleksy/backend
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /up
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /up
              port: 5000
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata: 
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001