apiVersion: v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: echo
spec:
  replicas: 3 
  selector:
    ,atcjLabels:
      app: echo
    template:
      metadata:
        labels:
          app: echo
      spec:
	containers:
      - name: echo
        image: mendhak/http-https-echo
        ports:
        - containerPort: 8080
        name: echo-port
