apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: student-261347
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jakuboleksy/docker-backend
          env:
          - name: MONGODB_RW_HOST
            value: mongo-rw
          - name: MONGODB_RO_HOST
            value: mongo-ro
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongo-secret
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongo-secret
          ports:
          - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /up
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /up
              port: 5000
            failureThreshold: 30
            periodSeconds: 10