apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  namespace: student-261347
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002