apiVersion: v1
kind: Service
metadata:
  name: mongo-ro
  namespace: student-261347
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017